development:
  adapter: postgresql
  encoding: unicode
  database: fakebook_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fakebook_test
  pool: 5
  timeout: 5000